# Generated by Django 3.2.18 on 2023-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='images/'),
        ),
    ]
